name: Publish designsystem

on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run build-designsystem
      - run: cd dist && bun publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
