name: Publish designsystem

on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Build applicaiton
        run: bun run build-designsystem
      - run: npm publish dist
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
